### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [3]:
import numpy as np # type: ignore
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [9]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.random.random((3,4))

array([[0.56170335, 0.79122302, 0.18785756, 0.19167583],
       [0.42329517, 0.81096359, 0.15644583, 0.29990426],
       [0.1178903 , 0.09787046, 0.13087081, 0.41411298]])

In [13]:
np.linspace(-10,10,10,dtype=float)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [18]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(10, dtype = np.float32).reshape(5,2)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

[0 1 2 3 4 5 6 7 8 9]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int32
float32
int64


In [19]:
a3.ndim

3

In [21]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
print(a2.size)
a2

10


array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)

In [23]:
a3.itemsize

8

In [24]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float32
int64


### Changing Datatype

In [25]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [27]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [28]:
a1 ** 2
a1 ** 3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [29]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [34]:
a1 = np.random.random((7,11))
a1 = np.round(a1*100)
a1

array([[66., 25., 16., 13., 21.,  6., 51., 50., 65., 42., 55.],
       [25., 30., 30., 26., 79., 81., 44., 72., 25., 97., 83.],
       [37., 20., 34., 88., 93., 90., 70., 29., 31., 62., 69.],
       [56., 55., 83., 13., 66., 99., 13., 86., 81.,  3., 96.],
       [68.,  9., 72.,  9., 71., 62., 93., 44.,  1., 88.,  6.],
       [41.,  7., 33., 71., 74., 96., 54., 35., 54., 67., 17.],
       [62., 78., 62., 88.,  7., 92., 66., 84., 95.,  1., 71.]])

In [35]:
np.prod(a1,axis = 0)

array([5.90960093e+11, 4.05405000e+09, 1.99542943e+11, 2.17433399e+10,
       3.74508241e+11, 2.37118109e+12, 6.76838242e+11, 1.16144582e+12,
       2.09323238e+10, 4.46777654e+09, 2.18987652e+11])

In [38]:
print(np.min(a1, axis = 1))
print(np.sum(a1,axis = 1))
print(np.max(a1, axis = 1))
print(np.mean(a1, axis = 1))
print(np.std(a1, axis = 1))
print(np.var(a1, axis = 1))
print(np.cumsum(a1, axis = 1))
print(np.median(a1, axis = 1))
print(np.percentile(a1, 50, axis = 1))
print(np.any(a1 > 0, axis = 1))

[ 6. 25. 20.  3.  1.  7.  1.]
[410. 592. 623. 651. 523. 549. 706.]
[66. 97. 93. 99. 93. 96. 95.]
[37.27272727 53.81818182 56.63636364 59.18181818 47.54545455 49.90909091
 64.18181818]
[20.70612957 27.11195034 26.00794538 33.30252019 33.51353495 25.20264974
 30.44463882]
[ 428.74380165  735.05785124  676.41322314 1109.05785124 1123.15702479
  635.17355372  926.87603306]
[[ 66.  91. 107. 120. 141. 147. 198. 248. 313. 355. 410.]
 [ 25.  55.  85. 111. 190. 271. 315. 387. 412. 509. 592.]
 [ 37.  57.  91. 179. 272. 362. 432. 461. 492. 554. 623.]
 [ 56. 111. 194. 207. 273. 372. 385. 471. 552. 555. 651.]
 [ 68.  77. 149. 158. 229. 291. 384. 428. 429. 517. 523.]
 [ 41.  48.  81. 152. 226. 322. 376. 411. 465. 532. 549.]
 [ 62. 140. 202. 290. 297. 389. 455. 539. 634. 635. 706.]]
[42. 44. 62. 66. 62. 54. 71.]
[42. 44. 62. 66. 62. 54. 71.]
[ True  True  True  True  True  True  True]


In [41]:
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))
print(np.log(a1))
print(np.log10(a1))

[[-0.02655115 -0.13235175 -0.28790332  0.42016704  0.83665564 -0.2794155
   0.67022918 -0.26237485  0.82682868 -0.91652155 -0.99975517]
 [-0.13235175 -0.98803162 -0.98803162  0.76255845 -0.44411267 -0.62988799
   0.01770193  0.25382336 -0.13235175  0.37960774  0.96836446]
 [-0.64353813  0.91294525  0.52908269  0.0353983  -0.94828214  0.89399666
   0.77389068 -0.66363388 -0.40403765 -0.7391807  -0.11478481]
 [-0.521551   -0.99975517  0.96836446  0.42016704 -0.02655115 -0.99920683
   0.42016704 -0.92345845 -0.62988799  0.14112001  0.98358775]
 [-0.89792768  0.41211849  0.25382336  0.41211849  0.95105465 -0.7391807
  -0.94828214  0.01770193  0.84147098  0.0353983  -0.2794155 ]
 [-0.15862267  0.6569866   0.99991186  0.95105465 -0.98514626  0.98358775
  -0.55878905 -0.42818267 -0.55878905 -0.85551998 -0.96139749]
 [-0.7391807   0.51397846 -0.7391807   0.0353983   0.6569866  -0.77946607
  -0.02655115  0.73319032  0.68326171  0.84147098  0.95105465]]
[[-0.99964746  0.99120281 -0.95765948  0.9

In [42]:
a2 = np.arange(12).reshape(3,4)
a4 = np.arange(8).reshape(4, 2)
np.dot(a2, a4)

array([[ 28,  34],
       [ 76,  98],
       [124, 162]])

In [43]:
np.exp(a1)

array([[4.60718663e+28, 7.20048993e+10, 8.88611052e+06, 4.42413392e+05,
        1.31881573e+09, 4.03428793e+02, 1.40934908e+22, 5.18470553e+21,
        1.69488924e+28, 1.73927494e+18, 7.69478527e+23],
       [7.20048993e+10, 1.06864746e+13, 1.06864746e+13, 1.95729609e+11,
        2.03828107e+34, 1.50609731e+35, 1.28516001e+19, 1.85867175e+31,
        7.20048993e+10, 1.33833472e+42, 1.11286375e+36],
       [1.17191424e+16, 4.85165195e+08, 5.83461743e+14, 1.65163625e+38,
        2.45124554e+40, 1.22040329e+39, 2.51543867e+30, 3.93133430e+12,
        2.90488497e+13, 8.43835667e+26, 9.25378173e+29],
       [2.09165950e+24, 7.69478527e+23, 1.11286375e+36, 4.42413392e+05,
        4.60718663e+28, 9.88903032e+42, 4.42413392e+05, 2.23524660e+37,
        1.50609731e+35, 2.00855369e+01, 4.92345829e+41],
       [3.40427605e+29, 8.10308393e+03, 1.85867175e+31, 8.10308393e+03,
        6.83767123e+30, 8.43835667e+26, 2.45124554e+40, 1.28516001e+19,
        2.71828183e+00, 1.65163625e+38, 4.03428793e+

In [44]:
np.ceil(np.random.random((2,3))*100)

array([[36., 95., 13.],
       [48., 85., 60.]])

### Indexing and Slicing

In [53]:
a5 = np.arange(10)
a6 = np.arange(10).reshape(2,5)
a7 = np.arange(12).reshape(2,3,2)
a7

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [54]:
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
a5[4]

np.int64(4)

In [57]:
a6[1,2]

np.int64(7)

In [58]:
a7[1,2,1]

np.int64(11)

In [59]:
a3[1,1,0]

np.int64(6)

In [60]:
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a1[2:5:2]

array([[37., 20., 34., 88., 93., 90., 70., 29., 31., 62., 69.],
       [68.,  9., 72.,  9., 71., 62., 93., 44.,  1., 88.,  6.]])

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [65]:
a6[::2,1::2]

array([[1, 3]])

In [66]:
a6[1,::3]

array([5, 8])

In [67]:
a6[0,:]

array([0, 1, 2, 3, 4])

In [68]:
a2[0,:]

array([0, 1, 2, 3])

In [69]:
a6[:,2]

array([2, 7])

In [70]:
a6[1:,1:3]

array([[6, 7]])

In [71]:
a8 = np.arange(27).reshape(3,3,3)
a8

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [73]:
a8[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [74]:
a8[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [76]:
a8[0,1,:]

array([3, 4, 5])

### Iterating

In [77]:
a1
for i in a1:
    print(i)

[66. 25. 16. 13. 21.  6. 51. 50. 65. 42. 55.]
[25. 30. 30. 26. 79. 81. 44. 72. 25. 97. 83.]
[37. 20. 34. 88. 93. 90. 70. 29. 31. 62. 69.]
[56. 55. 83. 13. 66. 99. 13. 86. 81.  3. 96.]
[68.  9. 72.  9. 71. 62. 93. 44.  1. 88.  6.]
[41.  7. 33. 71. 74. 96. 54. 35. 54. 67. 17.]
[62. 78. 62. 88.  7. 92. 66. 84. 95.  1. 71.]


In [79]:
a0 = np.arange(10)
a0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [83]:
a8

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
for i in a8:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [85]:
for i in np.nditer(a8):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [86]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [87]:
np.transpose(a8)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [88]:
a8.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [89]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [91]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [92]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [95]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [98]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]