### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
import numpy as np # type: ignore
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
type(b)

numpy.ndarray

In [7]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [9]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.random.random((3,4))

array([[0.56170335, 0.79122302, 0.18785756, 0.19167583],
       [0.42329517, 0.81096359, 0.15644583, 0.29990426],
       [0.1178903 , 0.09787046, 0.13087081, 0.41411298]])

In [13]:
np.linspace(-10,10,10,dtype=float)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [18]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(10, dtype = np.float32).reshape(5,2)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

[0 1 2 3 4 5 6 7 8 9]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int32
float32
int64


In [19]:
a3.ndim

3

In [21]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
print(a2.size)
a2

10


array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)

In [23]:
a3.itemsize

8

In [24]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float32
int64


### Changing Datatype

In [25]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [27]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [28]:
a1 ** 2
a1 ** 3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [29]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [3]:
a1 = np.random.random((7,11))
a1 = np.round(a1*100,2)
a1

array([[96.72, 33.55, 35.74, 66.91, 64.48, 44.52, 37.6 , 19.04, 29.71,
         3.75, 28.36],
       [24.53, 42.37, 39.1 , 98.25, 18.78, 71.39, 25.7 , 26.14, 52.42,
        75.05, 26.31],
       [90.37, 77.91, 96.48, 53.97, 51.87, 83.11, 23.09,  1.61,  3.52,
        88.35, 79.24],
       [68.64, 50.47, 75.25, 31.94, 98.29, 33.97, 22.45, 43.31, 75.38,
        16.36, 24.42],
       [57.89, 18.64, 13.48, 50.5 , 13.01, 84.77, 33.63, 53.57, 42.04,
        29.2 , 39.46],
       [84.57, 74.26, 32.15, 14.14, 67.66, 39.15, 42.09, 24.68, 92.33,
         0.63, 94.53],
       [87.98,  9.82, 44.48, 76.01, 11.19, 82.86, 28.14, 41.31,  7.01,
        21.58, 62.84]])

In [4]:
np.prod(a1,axis = 0)

array([6.33897780e+12, 7.59783466e+10, 1.95573835e+11, 6.15067017e+11,
       6.08114804e+10, 2.46751752e+12, 1.99522158e+10, 1.89543364e+09,
       1.12440308e+10, 1.61490381e+08, 3.38438776e+11])

In [5]:
print(np.min(a1, axis = 1))
print(np.sum(a1,axis = 1))
print(np.max(a1, axis = 1))
print(np.mean(a1, axis = 1))
print(np.std(a1, axis = 1))
print(np.var(a1, axis = 1))
print(np.cumsum(a1, axis = 1))
print(np.median(a1, axis = 1))
print(np.percentile(a1, 50, axis = 1))
print(np.any(a1 > 0, axis = 1))

[ 3.75 18.78  1.61 16.36 13.01  0.63  7.01]
[460.38 500.04 649.52 540.48 436.19 566.19 473.22]
[96.72 98.25 96.48 98.29 84.77 94.53 87.98]
[41.85272727 45.45818182 59.04727273 49.13454545 39.65363636 51.47181818
 43.02      ]
[24.46429052 24.70459318 33.48822238 25.45215024 20.59825777 31.20282791
 28.90116764]
[ 598.50151074  610.31692397 1121.46103802  647.81195207  424.28822314
  973.61646942  835.27749091]
[[ 96.72 130.27 166.01 232.92 297.4  341.92 379.52 398.56 428.27 432.02
  460.38]
 [ 24.53  66.9  106.   204.25 223.03 294.42 320.12 346.26 398.68 473.73
  500.04]
 [ 90.37 168.28 264.76 318.73 370.6  453.71 476.8  478.41 481.93 570.28
  649.52]
 [ 68.64 119.11 194.36 226.3  324.59 358.56 381.01 424.32 499.7  516.06
  540.48]
 [ 57.89  76.53  90.01 140.51 153.52 238.29 271.92 325.49 367.53 396.73
  436.19]
 [ 84.57 158.83 190.98 205.12 272.78 311.93 354.02 378.7  471.03 471.66
  566.19]
 [ 87.98  97.8  142.28 218.29 229.48 312.34 340.48 381.79 388.8  410.38
  473.22]]
[35.74 39.1

In [6]:
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))
print(np.log(a1))
print(np.log10(a1))

[[ 0.62049383  0.84550979 -0.92554817 -0.80552106  0.99700993  0.51216435
  -0.09894966  0.18929496 -0.9908838  -0.57156132 -0.08556138]
 [-0.56690278 -0.99913896  0.9856003  -0.75825197 -0.06949985  0.7621522
   0.53732218  0.84537071  0.83441755 -0.34122865  0.92355834]
 [ 0.6714672   0.58899635  0.78911831 -0.53366205  0.99943149  0.98990585
  -0.89068578  0.99923163 -0.36944096  0.37593511 -0.64435815]
 [-0.45737258  0.20309478 -0.14768153  0.50041104 -0.78371696  0.55429791
  -0.44291863 -0.6227849  -0.01822268 -0.60680656 -0.65391016]
 [ 0.97378843 -0.20802556  0.79172605  0.23237376  0.42922035  0.05297684
   0.80013436 -0.16220505 -0.93178357 -0.79902148  0.98198689]
 [ 0.25031117 -0.90789028  0.66989954  0.99999599 -0.99330753  0.99281962
  -0.94876224 -0.43743223 -0.94040286  0.58914476  0.27848889]
 [ 0.01540509 -0.38501312  0.47740834  0.57432251 -0.98115879  0.92406837
   0.13393022 -0.45225807  0.66449265  0.39966245  0.00814684]]
[[-0.78421133 -0.53395991 -0.37862988 -0.

In [7]:
a2 = np.arange(12).reshape(3,4)
a4 = np.arange(8).reshape(4, 2)
np.dot(a2, a4)

array([[ 28,  34],
       [ 76,  98],
       [124, 162]])

In [43]:
np.exp(a1)

array([[4.60718663e+28, 7.20048993e+10, 8.88611052e+06, 4.42413392e+05,
        1.31881573e+09, 4.03428793e+02, 1.40934908e+22, 5.18470553e+21,
        1.69488924e+28, 1.73927494e+18, 7.69478527e+23],
       [7.20048993e+10, 1.06864746e+13, 1.06864746e+13, 1.95729609e+11,
        2.03828107e+34, 1.50609731e+35, 1.28516001e+19, 1.85867175e+31,
        7.20048993e+10, 1.33833472e+42, 1.11286375e+36],
       [1.17191424e+16, 4.85165195e+08, 5.83461743e+14, 1.65163625e+38,
        2.45124554e+40, 1.22040329e+39, 2.51543867e+30, 3.93133430e+12,
        2.90488497e+13, 8.43835667e+26, 9.25378173e+29],
       [2.09165950e+24, 7.69478527e+23, 1.11286375e+36, 4.42413392e+05,
        4.60718663e+28, 9.88903032e+42, 4.42413392e+05, 2.23524660e+37,
        1.50609731e+35, 2.00855369e+01, 4.92345829e+41],
       [3.40427605e+29, 8.10308393e+03, 1.85867175e+31, 8.10308393e+03,
        6.83767123e+30, 8.43835667e+26, 2.45124554e+40, 1.28516001e+19,
        2.71828183e+00, 1.65163625e+38, 4.03428793e+

In [44]:
np.ceil(np.random.random((2,3))*100)

array([[36., 95., 13.],
       [48., 85., 60.]])

### Indexing and Slicing

In [7]:
import numpy as np
a5 = np.arange(10)
a6 = np.arange(10).reshape(2,5)
a7 = np.arange(12).reshape(2,3,2)
a7

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [3]:
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
a5[4]

np.int64(4)

In [ ]:
a6[1,2]

np.int64(7)

In [58]:
a7[1,2,1]

np.int64(11)

In [59]:
a3[1,1,0]

np.int64(6)

In [60]:
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a1

array([[ 47.,  21.,  16.,  67.,  32.,  94.,  96.,  48.,  13.,  70.,  97.],
       [ 15.,  20.,  46.,   9.,  74.,  19.,  80.,  40.,  87.,   1.,  45.],
       [ 20.,  48.,  37.,  53.,  90.,   2.,  57.,  58.,  73.,  29.,  11.],
       [ 96.,  11.,  17.,  79.,  44.,  78.,  49.,  85.,   3.,   2.,  58.],
       [ 93.,  62.,  27.,  32.,  30.,  40.,  43.,  84.,  39.,  14.,  70.],
       [ 77.,  12.,  85.,  94.,  51.,  56.,   0.,  43.,  93., 100.,   8.],
       [ 41.,  59.,  33.,  83.,   9.,  47.,  11.,  39.,  72.,  97.,  82.]])

In [5]:
a1[2:5:2]

array([[20., 48., 37., 53., 90.,  2., 57., 58., 73., 29., 11.],
       [93., 62., 27., 32., 30., 40., 43., 84., 39., 14., 70.]])

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [8]:
a6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
a6[::2,1::2]

array([[1, 3]])

In [66]:
a6[1,::3]

array([5, 8])

In [67]:
a6[0,:]

array([0, 1, 2, 3, 4])

In [68]:
a2[0,:]

array([0, 1, 2, 3])

In [69]:
a6[:,2]

array([2, 7])

In [70]:
a6[1:,1:3]

array([[6, 7]])

In [71]:
a8 = np.arange(27).reshape(3,3,3)
a8

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [73]:
a8[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [74]:
a8[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [76]:
a8[0,1,:]

array([3, 4, 5])

### Iterating

In [77]:
a1
for i in a1:
    print(i)

[66. 25. 16. 13. 21.  6. 51. 50. 65. 42. 55.]
[25. 30. 30. 26. 79. 81. 44. 72. 25. 97. 83.]
[37. 20. 34. 88. 93. 90. 70. 29. 31. 62. 69.]
[56. 55. 83. 13. 66. 99. 13. 86. 81.  3. 96.]
[68.  9. 72.  9. 71. 62. 93. 44.  1. 88.  6.]
[41.  7. 33. 71. 74. 96. 54. 35. 54. 67. 17.]
[62. 78. 62. 88.  7. 92. 66. 84. 95.  1. 71.]


In [79]:
a0 = np.arange(10)
a0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [83]:
a8

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
for i in a8:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [85]:
for i in np.nditer(a8):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [86]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [87]:
np.transpose(a8)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [88]:
a8.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [89]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [91]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [92]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [95]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [98]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]