### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [3]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
type(b)

numpy.ndarray

In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [7]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random((3,4))

array([[0.04992311, 0.66677101, 0.99398052, 0.95056664],
       [0.1762371 , 0.12631935, 0.37245085, 0.53820206],
       [0.75342265, 0.46447163, 0.32500424, 0.50838282]])

In [11]:
np.linspace(-10,10,10,dtype=float)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [13]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(10, dtype = np.float32).reshape(5,2)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

[0 1 2 3 4 5 6 7 8 9]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int32
float32
int64


In [14]:
a3.ndim

3

In [15]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
print(a2.size)
a2

10


array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)

In [17]:
a3.itemsize

8

In [18]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float32
int64


### Changing Datatype

In [19]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [21]:
a1 ** 2
a1 ** 3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [22]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [24]:
a1 = np.random.random((7,11))
a1 = np.round(a1*100,2)
a1

array([[21.49,  7.06, 11.96, 68.39, 77.93, 52.81, 98.4 , 68.46, 74.32,
        82.45, 93.19],
       [24.1 , 42.59, 28.54, 15.26, 65.78, 15.94, 65.1 , 51.9 , 21.55,
        95.51, 83.5 ],
       [54.34, 82.89, 99.42, 39.48, 29.61, 88.51, 73.17, 56.86, 36.8 ,
         0.16,  0.71],
       [11.34, 68.02, 61.46, 63.38, 36.3 , 46.94, 43.7 ,  0.96, 45.76,
        45.19, 18.68],
       [29.47, 34.6 , 57.21, 20.78, 40.36, 24.46, 12.54, 98.49, 52.16,
        61.4 , 13.47],
       [46.49, 57.49, 74.75,  9.45, 50.65, 82.43, 43.04, 26.21, 32.95,
        69.35,  9.63],
       [39.78, 93.55, 64.64, 61.74, 75.83, 99.92, 58.76, 27.85, 81.63,
        60.76, 92.19]])

In [25]:
np.prod(a1,axis = 0)

array([1.73936452e+10, 3.15473808e+11, 5.76548645e+11, 3.16606986e+10,
       8.54112821e+11, 7.04586128e+11, 6.49594240e+11, 1.39433362e+10,
       3.78381250e+11, 1.47310747e+10, 1.23415215e+09])

In [26]:
print(np.min(a1, axis = 1))
print(np.sum(a1,axis = 1))
print(np.max(a1, axis = 1))
print(np.mean(a1, axis = 1))
print(np.std(a1, axis = 1))
print(np.var(a1, axis = 1))
print(np.cumsum(a1, axis = 1))
print(np.median(a1, axis = 1))
print(np.percentile(a1, 50, axis = 1))
print(np.any(a1 > 0, axis = 1))

[ 7.06 15.26  0.16  0.96 12.54  9.45 27.85]
[656.46 509.77 561.95 441.73 444.94 502.44 756.65]
[98.4  95.51 99.42 68.02 98.49 82.43 99.92]
[59.67818182 46.34272727 51.08636364 40.15727273 40.44909091 45.67636364
 68.78636364]
[30.73746864 26.78111583 31.92471664 20.73144563 24.36434483 23.51217877
 21.5191079 ]
[ 944.79197851  717.22816529 1019.18753223  429.79283802  593.62129917
  552.82255041  463.07200496]
[[ 21.49  28.55  40.51 108.9  186.83 239.64 338.04 406.5  480.82 563.27
  656.46]
 [ 24.1   66.69  95.23 110.49 176.27 192.21 257.31 309.21 330.76 426.27
  509.77]
 [ 54.34 137.23 236.65 276.13 305.74 394.25 467.42 524.28 561.08 561.24
  561.95]
 [ 11.34  79.36 140.82 204.2  240.5  287.44 331.14 332.1  377.86 423.05
  441.73]
 [ 29.47  64.07 121.28 142.06 182.42 206.88 219.42 317.91 370.07 431.47
  444.94]
 [ 46.49 103.98 178.73 188.18 238.83 321.26 364.3  390.51 423.46 492.81
  502.44]
 [ 39.78 133.33 197.97 259.71 335.54 435.46 494.22 522.07 603.7  664.46
  756.65]]
[68.46 42.5

In [27]:
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))
print(np.log(a1))
print(np.log10(a1))

[[ 0.48043319  0.70101138 -0.56988887 -0.66316417  0.57271691  0.56222605
  -0.84716555 -0.60918968 -0.88111919  0.69512302 -0.87126785]
 [-0.858707   -0.98411128 -0.26255208  0.43313066  0.19224148 -0.22996015
   0.76654629  0.99797049  0.42697836  0.95276703  0.96945567]
 [-0.80336511  0.93511767 -0.89612733  0.97801177 -0.97248401  0.51876497
  -0.79156694  0.3063271  -0.78277451  0.15931821  0.65183377]
 [-0.94126952 -0.88894583 -0.98027597  0.52110654 -0.98529838  0.18285517
  -0.27856261  0.81919157  0.9786711   0.9348026  -0.16874466]
 [-0.93045992 -0.04246803  0.61416876  0.93602085  0.46240395 -0.62313229
  -0.02636756 -0.89149192  0.94805828 -0.9903629   0.78557781]
 [ 0.59228336  0.80834312 -0.60377136 -0.02521937  0.37511195  0.68060714
  -0.8089108   0.88066248  0.99932579  0.23280566 -0.20378454]
 [ 0.87269967 -0.64251785  0.97196433 -0.88748241  0.41848475 -0.57365808
   0.8017756   0.41171383 -0.05138635 -0.87707544 -0.88374859]]
[[-0.87703133  0.71315009  0.82172177  0

In [28]:
a2 = np.arange(12).reshape(3,4)
a4 = np.arange(8).reshape(4, 2)
np.dot(a2, a4)

array([[ 28,  34],
       [ 76,  98],
       [124, 162]])

In [29]:
np.exp(a1)

array([[2.15272431e+09, 1.16444517e+03, 1.56373085e+05, 5.02805034e+29,
        6.99147767e+33, 8.61175348e+22, 5.42721491e+42, 5.39262513e+29,
        1.89132383e+32, 6.42066532e+35, 2.96416769e+40],
       [2.92750074e+10, 3.13763185e+18, 2.48178705e+12, 4.23968698e+06,
        3.69735388e+28, 8.36862373e+06, 1.87314230e+28, 3.46643939e+22,
        2.28584135e+09, 3.01624050e+41, 1.83480214e+36],
       [3.97706003e+23, 9.96941339e+35, 1.50507240e+43, 1.39941378e+17,
        7.23535108e+12, 2.75045531e+38, 5.98862668e+31, 4.94292751e+24,
        9.59482226e+15, 1.17351087e+00, 2.03399126e+00],
       [8.41200311e+04, 3.47304699e+29, 4.91743760e+26, 3.35416377e+27,
        5.81955388e+15, 2.43098893e+20, 9.52069953e+18, 2.61169647e+00,
        7.46991211e+19, 4.22442532e+19, 1.29604751e+08],
       [6.29011205e+12, 1.06313661e+15, 7.01434802e+24, 1.05837442e+09,
        3.37384627e+17, 4.19607293e+10, 2.79288339e+05, 5.93831899e+42,
        4.49572954e+22, 4.63106833e+26, 7.07858858e+

In [30]:
np.ceil(np.random.random((2,3))*100)

array([[100.,  39.,  49.],
       [ 65.,  62.,   2.]])

### Indexing and Slicing

In [31]:
import numpy as np
a5 = np.arange(10)
a6 = np.arange(10).reshape(2,5)
a7 = np.arange(12).reshape(2,3,2)
a7

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [32]:
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
a5[4]

np.int64(4)

In [35]:
a6[1,2]

np.int64(7)

In [36]:
a7[1,2,1]

np.int64(11)

In [37]:
a3[1,1,0]

np.int64(6)

In [38]:
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1

array([[21.49,  7.06, 11.96, 68.39, 77.93, 52.81, 98.4 , 68.46, 74.32,
        82.45, 93.19],
       [24.1 , 42.59, 28.54, 15.26, 65.78, 15.94, 65.1 , 51.9 , 21.55,
        95.51, 83.5 ],
       [54.34, 82.89, 99.42, 39.48, 29.61, 88.51, 73.17, 56.86, 36.8 ,
         0.16,  0.71],
       [11.34, 68.02, 61.46, 63.38, 36.3 , 46.94, 43.7 ,  0.96, 45.76,
        45.19, 18.68],
       [29.47, 34.6 , 57.21, 20.78, 40.36, 24.46, 12.54, 98.49, 52.16,
        61.4 , 13.47],
       [46.49, 57.49, 74.75,  9.45, 50.65, 82.43, 43.04, 26.21, 32.95,
        69.35,  9.63],
       [39.78, 93.55, 64.64, 61.74, 75.83, 99.92, 58.76, 27.85, 81.63,
        60.76, 92.19]])

In [40]:
a1[2:5:2]

array([[54.34, 82.89, 99.42, 39.48, 29.61, 88.51, 73.17, 56.86, 36.8 ,
         0.16,  0.71],
       [29.47, 34.6 , 57.21, 20.78, 40.36, 24.46, 12.54, 98.49, 52.16,
        61.4 , 13.47]])

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [43]:
a6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
a6[::2,1::2]

array([[1, 3]])

In [45]:
a6[1,::3]

array([5, 8])

In [46]:
a6[0,:]

array([0, 1, 2, 3, 4])

In [47]:
a2[0,:]

array([0, 1, 2, 3])

In [48]:
a6[:,2]

array([2, 7])

In [49]:
a6[1:,1:3]

array([[6, 7]])

In [50]:
a8 = np.arange(27).reshape(3,3,3)
a8

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
a8[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [52]:
a8[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [53]:
a8[0,1,:]

array([3, 4, 5])

### Iterating

In [54]:
for i in a1:
    print(i)

[21.49  7.06 11.96 68.39 77.93 52.81 98.4  68.46 74.32 82.45 93.19]
[24.1  42.59 28.54 15.26 65.78 15.94 65.1  51.9  21.55 95.51 83.5 ]
[54.34 82.89 99.42 39.48 29.61 88.51 73.17 56.86 36.8   0.16  0.71]
[11.34 68.02 61.46 63.38 36.3  46.94 43.7   0.96 45.76 45.19 18.68]
[29.47 34.6  57.21 20.78 40.36 24.46 12.54 98.49 52.16 61.4  13.47]
[46.49 57.49 74.75  9.45 50.65 82.43 43.04 26.21 32.95 69.35  9.63]
[39.78 93.55 64.64 61.74 75.83 99.92 58.76 27.85 81.63 60.76 92.19]


In [55]:
a0 = np.arange(10)
a0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [57]:
a8

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
for i in a8:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [59]:
for i in np.nditer(a8):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [60]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [61]:
np.transpose(a8)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [62]:
a8.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [63]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [65]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [66]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [68]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]