### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [4]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([35, 89, 87, 52, 25, 83, 34, 94, 59,  5, 23,  5, 65, 26, 94],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[54, 50, 89,  8],
       [45,  2, 18, 56],
       [73, 83, 98, 28],
       [14, 74, 65,  5],
       [51, 87, 73, 91],
       [43,  4, 99, 45]], dtype=int32)

In [3]:
np.sort(a)

array([ 1, 14, 15, 17, 30, 30, 38, 45, 58, 65, 74, 84, 88, 90, 96],
      dtype=int32)

In [4]:
np.sort(a)[::-1]

array([96, 90, 88, 84, 74, 65, 58, 45, 38, 30, 30, 17, 15, 14,  1],
      dtype=int32)

In [5]:
np.sort(b,axis=0)

array([[14,  2, 18,  5],
       [43,  4, 65,  8],
       [45, 50, 73, 28],
       [51, 74, 89, 45],
       [54, 83, 98, 56],
       [73, 87, 99, 91]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
np.append(a,200)

array([ 65,  15,  30,  58,  90,  88,   1,  14,  38,  96,  30,  17,  84,
        45,  74, 200])

In [7]:
b

array([[54, 50, 89,  8],
       [45,  2, 18, 56],
       [73, 83, 98, 28],
       [14, 74, 65,  5],
       [51, 87, 73, 91],
       [43,  4, 99, 45]], dtype=int32)

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
e = np.array([1,1,2,3,4,4,4,4,5,5,5,9,7,8,9,8])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 7, 8, 9])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
a.shape

(15,)

In [16]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [17]:
np.expand_dims(a,axis = 1)

array([[65],
       [15],
       [30],
       [58],
       [90],
       [88],
       [ 1],
       [14],
       [38],
       [96],
       [30],
       [17],
       [84],
       [45],
       [74]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([65, 15, 30, 58, 90, 88,  1, 14, 38, 96, 30, 17, 84, 45, 74],
      dtype=int32)

In [19]:
np.where(a>50)

(array([ 0,  3,  4,  5,  9, 12, 14]),)

In [20]:
np.where(a>50,0,a)

array([ 0, 15, 30,  0,  0,  0,  1, 14, 38,  0, 30, 17,  0, 45,  0],
      dtype=int32)

In [21]:
np.where(a%2 == 0,0,a)

array([65, 15,  0,  0,  0,  0,  1,  0,  0,  0,  0, 17,  0, 45,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [6]:
a = np.random.randint(1,100,15)
a

array([66, 60, 20, 20, 79, 57, 52, 95, 61, 35, 71, 14, 93, 73, 38],
      dtype=int32)

In [7]:
np.argmax(a)

np.int64(7)

In [9]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[64, 82, 47, 62],
       [74, 97, 67, 70],
       [62, 56, 83,  8],
       [97, 45, 20, 28],
       [92, 33, 35, 50],
       [77, 63, 37, 35]], dtype=int32)

In [10]:
np.argmax(b,axis=0)

array([3, 1, 2, 1])

In [11]:
np.argmax(b,axis=1)

array([1, 1, 2, 0, 0, 0])

In [12]:
np.argmin(a)

np.int64(11)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [13]:
a

array([66, 60, 20, 20, 79, 57, 52, 95, 61, 35, 71, 14, 93, 73, 38],
      dtype=int32)

In [14]:
np.cumsum(a)

array([ 66, 126, 146, 166, 245, 302, 354, 449, 510, 545, 616, 630, 723,
       796, 834])

In [15]:
b

array([[64, 82, 47, 62],
       [74, 97, 67, 70],
       [62, 56, 83,  8],
       [97, 45, 20, 28],
       [92, 33, 35, 50],
       [77, 63, 37, 35]], dtype=int32)

In [16]:
np.cumsum(b,axis=1)

array([[ 64, 146, 193, 255],
       [ 74, 171, 238, 308],
       [ 62, 118, 201, 209],
       [ 97, 142, 162, 190],
       [ 92, 125, 160, 210],
       [ 77, 140, 177, 212]])

In [17]:
np.cumprod(a)

array([                 66,                3960,               79200,
                   1584000,           125136000,          7132752000,
              370903104000,      35235794880000,    2149383487680000,
         75228422068800000, 5341217966884800000,  990075241548993536,
       -156722904491359232, 7005972045840327680, 7972520709998729216])

In [18]:
np.cumprod(b)

array([                  64,                 5248,               246656,
                   15292672,           1131657728,         109770799616,
              7354643574272,      514825050199040,    31919153112340480,
        1787472574291066880,   786271076482138112,  6290168611857104896,
        1403800917723971584,  7830809076450066432,  9042228939324915712,
       -5072006730836082688, -5456017394180816896,  4418866729128558592,
        7086382929823137792,  3831009090675408896,  -160205197346340864,
        8353816640890077184, -4503433540129521664,  8400522758852706304])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [20]:
a

array([66, 60, 20, 20, 79, 57, 52, 95, 61, 35, 71, 14, 93, 73, 38],
      dtype=int32)

In [21]:
np.percentile(a,50)

np.float64(60.0)

In [22]:
np.median(a)

np.float64(60.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [23]:
a

array([66, 60, 20, 20, 79, 57, 52, 95, 61, 35, 71, 14, 93, 73, 38],
      dtype=int32)

In [24]:
np.histogram(a,bins=[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [28]:
salary = np.array([10000, 20000, 30000, 40000, 50000])
experiance = np.array([1, 5, 3, -2, 8])
np.corrcoef(salary, experiance)

array([[1.        , 0.29065918],
       [0.29065918, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [29]:
a

array([66, 60, 20, 20, 79, 57, 52, 95, 61, 35, 71, 14, 93, 73, 38],
      dtype=int32)

In [30]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60, 20, 20], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [31]:
a

array([66, 60, 20, 20, 79, 57, 52, 95, 61, 35, 71, 14, 93, 73, 38],
      dtype=int32)

In [32]:
np.flip(a)

array([38, 73, 93, 14, 71, 35, 61, 95, 52, 57, 79, 20, 20, 60, 66],
      dtype=int32)

In [33]:
b

array([[64, 82, 47, 62],
       [74, 97, 67, 70],
       [62, 56, 83,  8],
       [97, 45, 20, 28],
       [92, 33, 35, 50],
       [77, 63, 37, 35]], dtype=int32)

In [34]:
np.flip(b,axis=1)

array([[62, 47, 82, 64],
       [70, 67, 97, 74],
       [ 8, 83, 56, 62],
       [28, 20, 45, 97],
       [50, 35, 33, 92],
       [35, 37, 63, 77]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [35]:
a

array([66, 60, 20, 20, 79, 57, 52, 95, 61, 35, 71, 14, 93, 73, 38],
      dtype=int32)

In [36]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [37]:
a

array([110, 530,  20,  20,  79,  57,  52,  95,  61,  35,  71,  14,  93,
        73,  38], dtype=int32)

In [38]:
np.delete(a,[0,2,4])

array([530,  20,  57,  52,  95,  61,  35,  71,  14,  93,  73,  38],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [39]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
np.intersect1d(m,n)

array([3, 4, 5])

In [41]:
np.setdiff1d(m,n)

array([1, 2])

In [42]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [43]:
m[np.isin(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [44]:
a

array([110, 530,  20,  20,  79,  57,  52,  95,  61,  35,  71,  14,  93,
        73,  38], dtype=int32)

In [45]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 25, 75, 57, 52, 75, 61, 35, 71, 25, 75, 73, 38],
      dtype=int32)

In [49]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [50]:
np.swapaxes(a, 0, 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [52]:
np.random.uniform(0, 1, 10)

array([0.54261851, 0.30567057, 0.45032251, 0.04821416, 0.31665539,
       0.51399901, 0.88844406, 0.67544635, 0.43616332, 0.37551368])

In [53]:
np.count_nonzero(a, axis=None, keepdims=False)


6

In [57]:
np.tile(a, 3)


array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [58]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])