### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([66, 82, 40,  5, 61, 47, 20, 85, 38, 79,  8, 26, 97, 53, 70],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[49, 22,  3, 15],
       [77, 77, 42,  1],
       [20, 16, 71, 21],
       [99, 23, 64, 67],
       [76,  7, 14, 89],
       [58, 24, 57, 24]], dtype=int32)

In [3]:
np.sort(a)

array([ 5,  8, 20, 26, 38, 40, 47, 53, 61, 66, 70, 79, 82, 85, 97],
      dtype=int32)

In [4]:
np.sort(a)[::-1]

array([97, 85, 82, 79, 70, 66, 61, 53, 47, 40, 38, 26, 20,  8,  5],
      dtype=int32)

In [5]:
np.sort(b,axis=0)

array([[20,  7,  3,  1],
       [49, 16, 14, 15],
       [58, 22, 42, 21],
       [76, 23, 57, 24],
       [77, 24, 64, 67],
       [99, 77, 71, 89]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
np.append(a,200)

array([ 66,  82,  40,   5,  61,  47,  20,  85,  38,  79,   8,  26,  97,
        53,  70, 200])

In [7]:
b

array([[49, 22,  3, 15],
       [77, 77, 42,  1],
       [20, 16, 71, 21],
       [99, 23, 64, 67],
       [76,  7, 14, 89],
       [58, 24, 57, 24]], dtype=int32)

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
e = np.array([1,1,2,3,4,4,4,4,5,5,5,9,7,8,9,8])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 7, 8, 9])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [17]:
a.shape

(15,)

In [14]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [16]:
np.expand_dims(a,axis = 1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([66, 82, 40,  5, 61, 47, 20, 85, 38, 79,  8, 26, 97, 53, 70],
      dtype=int32)

In [19]:
np.where(a>50)

(array([ 0,  1,  4,  7,  9, 12, 13, 14]),)

In [20]:
np.where(a>50,0,a)

array([ 0,  0, 40,  5,  0, 47, 20,  0, 38,  0,  8, 26,  0,  0,  0],
      dtype=int32)

In [21]:
np.where(a%2 == 0,0,a)

array([ 0,  0,  0,  5, 61, 47,  0, 85,  0, 79,  0,  0, 97, 53,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [35]:
a = np.random.randint(1,100,15)
a

array([84, 94, 15, 51,  8, 63, 47, 88, 38, 75, 95, 20, 73, 68, 63],
      dtype=int32)

In [36]:
np.argmax(a)

np.int64(10)

In [38]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[98, 10, 35, 51],
       [41,  7, 71, 87],
       [84,  7, 18, 46],
       [57, 90, 73, 32],
       [34, 87, 66, 36],
       [74, 18, 57, 14]], dtype=int32)

In [39]:
np.argmax(b,axis=0)

array([0, 3, 3, 1])

In [40]:
np.argmax(b,axis=1)

array([0, 3, 0, 1, 1, 0])

In [41]:
np.argmin(a)

np.int64(4)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [42]:
a

array([84, 94, 15, 51,  8, 63, 47, 88, 38, 75, 95, 20, 73, 68, 63],
      dtype=int32)

In [43]:
np.cumsum(a)

array([ 84, 178, 193, 244, 252, 315, 362, 450, 488, 563, 658, 678, 751,
       819, 882])

In [44]:
b

array([[98, 10, 35, 51],
       [41,  7, 71, 87],
       [84,  7, 18, 46],
       [57, 90, 73, 32],
       [34, 87, 66, 36],
       [74, 18, 57, 14]], dtype=int32)

In [45]:
np.cumsum(b,axis=1)

array([[ 98, 108, 143, 194],
       [ 41,  48, 119, 206],
       [ 84,  91, 109, 155],
       [ 57, 147, 220, 252],
       [ 34, 121, 187, 223],
       [ 74,  92, 149, 163]])

In [46]:
np.cumprod(a)

array([                  84,                 7896,               118440,
                    6040440,             48323520,           3044381760,
               143085942720,       12591562959360,      478479392455680,
          35885954434176000,  3409165671246720000, -5603662869903806464,
       -3239019881367736320,  1107576951508549632, -4009628349799579648])

In [47]:
np.cumprod(b)

array([                  98,                  980,                34300,
                    1749300,             71721300,            502049100,
                35645486100,        3101157290700,      260497212418800,
           1823480486931600,    32822648764768800,  1509841843179364800,
       -6172735307323964480, -2143855447870254720, -8927495104852181632,
       -8978682249626537984,  8319452765760086016,  4369371746454970368,
       -6769369913324781568, -3889643921467965440,  7314254990723383296,
        2529381317054038016, -3399217517596246016,  7751186974781210624])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [48]:
a

array([84, 94, 15, 51,  8, 63, 47, 88, 38, 75, 95, 20, 73, 68, 63],
      dtype=int32)

In [49]:
np.percentile(a,50)

np.float64(63.0)

In [50]:
np.median(a)

np.float64(63.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [51]:
a

array([84, 94, 15, 51,  8, 63, 47, 88, 38, 75, 95, 20, 73, 68, 63],
      dtype=int32)

In [52]:
np.histogram(a,bins=[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [53]:
salary = np.array([10000, 20000, 30000, 40000, 50000])
experiance = np.array([1, 5, 3, -2, 8])
np.corrcoef(salary, experiance)

array([[1.        , 0.29065918],
       [0.29065918, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [54]:
a

array([84, 94, 15, 51,  8, 63, 47, 88, 38, 75, 95, 20, 73, 68, 63],
      dtype=int32)

In [55]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([20], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [56]:
a

array([84, 94, 15, 51,  8, 63, 47, 88, 38, 75, 95, 20, 73, 68, 63],
      dtype=int32)

In [57]:
np.flip(a)

array([63, 68, 73, 20, 95, 75, 38, 88, 47, 63,  8, 51, 15, 94, 84],
      dtype=int32)

In [58]:
b

array([[98, 10, 35, 51],
       [41,  7, 71, 87],
       [84,  7, 18, 46],
       [57, 90, 73, 32],
       [34, 87, 66, 36],
       [74, 18, 57, 14]], dtype=int32)

In [59]:
np.flip(b,axis=1)

array([[51, 35, 10, 98],
       [87, 71,  7, 41],
       [46, 18,  7, 84],
       [32, 73, 90, 57],
       [36, 66, 87, 34],
       [14, 57, 18, 74]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [60]:
a

array([84, 94, 15, 51,  8, 63, 47, 88, 38, 75, 95, 20, 73, 68, 63],
      dtype=int32)

In [61]:
np.put(a,[0,1],[110,530])

In [62]:
a

array([110, 530,  15,  51,   8,  63,  47,  88,  38,  75,  95,  20,  73,
        68,  63], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [63]:
a

array([110, 530,  15,  51,   8,  63,  47,  88,  38,  75,  95,  20,  73,
        68,  63], dtype=int32)

In [64]:
np.delete(a,[0,2,4])

array([530,  51,  63,  47,  88,  38,  75,  95,  20,  73,  68,  63],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [66]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
np.intersect1d(m,n)

array([3, 4, 5])

In [68]:
np.setdiff1d(m,n)

array([1, 2])

In [69]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [70]:
m[np.isin(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [71]:
a

array([110, 530,  15,  51,   8,  63,  47,  88,  38,  75,  95,  20,  73,
        68,  63], dtype=int32)

In [72]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 51, 25, 63, 47, 75, 38, 75, 75, 25, 73, 68, 63],
      dtype=int32)

In [73]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [74]:
np.swapaxes(a, 0, 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
a = np.random.rand(2, 3, 4)  # Shape (2, 3, 4)
b = np.swapaxes(a, 0, 2)     # Now shape becomes (4, 3, 2)
a

array([[[0.70941216, 0.83092234, 0.45831642, 0.26006537],
        [0.75032842, 0.46610039, 0.84064952, 0.95282265],
        [0.15059803, 0.60063483, 0.74791049, 0.57934382]],

       [[0.3543952 , 0.23621917, 0.10029512, 0.09970613],
        [0.81689828, 0.11679141, 0.99812824, 0.17407359],
        [0.97056879, 0.84118155, 0.6353368 , 0.00277208]]])

In [80]:
b

array([[[0.70941216, 0.3543952 ],
        [0.75032842, 0.81689828],
        [0.15059803, 0.97056879]],

       [[0.83092234, 0.23621917],
        [0.46610039, 0.11679141],
        [0.60063483, 0.84118155]],

       [[0.45831642, 0.10029512],
        [0.84064952, 0.99812824],
        [0.74791049, 0.6353368 ]],

       [[0.26006537, 0.09970613],
        [0.95282265, 0.17407359],
        [0.57934382, 0.00277208]]])

In [76]:
np.random.uniform(0, 1, 10)

array([0.21691911, 0.22434106, 0.42470689, 0.65747997, 0.08549368,
       0.5580995 , 0.72659648, 0.79157346, 0.24062794, 0.47957807])

In [77]:
np.count_nonzero(a, axis=None, keepdims=False)


6

In [81]:
np.tile(a, 3)


array([[[0.70941216, 0.83092234, 0.45831642, 0.26006537, 0.70941216,
         0.83092234, 0.45831642, 0.26006537, 0.70941216, 0.83092234,
         0.45831642, 0.26006537],
        [0.75032842, 0.46610039, 0.84064952, 0.95282265, 0.75032842,
         0.46610039, 0.84064952, 0.95282265, 0.75032842, 0.46610039,
         0.84064952, 0.95282265],
        [0.15059803, 0.60063483, 0.74791049, 0.57934382, 0.15059803,
         0.60063483, 0.74791049, 0.57934382, 0.15059803, 0.60063483,
         0.74791049, 0.57934382]],

       [[0.3543952 , 0.23621917, 0.10029512, 0.09970613, 0.3543952 ,
         0.23621917, 0.10029512, 0.09970613, 0.3543952 , 0.23621917,
         0.10029512, 0.09970613],
        [0.81689828, 0.11679141, 0.99812824, 0.17407359, 0.81689828,
         0.11679141, 0.99812824, 0.17407359, 0.81689828, 0.11679141,
         0.99812824, 0.17407359],
        [0.97056879, 0.84118155, 0.6353368 , 0.00277208, 0.97056879,
         0.84118155, 0.6353368 , 0.00277208, 0.97056879, 0.84118155,


In [82]:
np.repeat(a, 3)

array([0.70941216, 0.70941216, 0.70941216, 0.83092234, 0.83092234,
       0.83092234, 0.45831642, 0.45831642, 0.45831642, 0.26006537,
       0.26006537, 0.26006537, 0.75032842, 0.75032842, 0.75032842,
       0.46610039, 0.46610039, 0.46610039, 0.84064952, 0.84064952,
       0.84064952, 0.95282265, 0.95282265, 0.95282265, 0.15059803,
       0.15059803, 0.15059803, 0.60063483, 0.60063483, 0.60063483,
       0.74791049, 0.74791049, 0.74791049, 0.57934382, 0.57934382,
       0.57934382, 0.3543952 , 0.3543952 , 0.3543952 , 0.23621917,
       0.23621917, 0.23621917, 0.10029512, 0.10029512, 0.10029512,
       0.09970613, 0.09970613, 0.09970613, 0.81689828, 0.81689828,
       0.81689828, 0.11679141, 0.11679141, 0.11679141, 0.99812824,
       0.99812824, 0.99812824, 0.17407359, 0.17407359, 0.17407359,
       0.97056879, 0.97056879, 0.97056879, 0.84118155, 0.84118155,
       0.84118155, 0.6353368 , 0.6353368 , 0.6353368 , 0.00277208,
       0.00277208, 0.00277208])