### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [69]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([86, 95, 48, 20, 26, 78, 27, 38, 68, 14, 64, 20, 41, 96, 30],
      dtype=int32)

In [70]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[59, 43, 35,  8],
       [42, 25, 55, 39],
       [46, 35, 57, 56],
       [38, 45, 35, 88],
       [77, 90, 15, 94],
       [90,  2, 57,  6]], dtype=int32)

In [71]:
np.sort(a)

array([14, 20, 20, 26, 27, 30, 38, 41, 48, 64, 68, 78, 86, 95, 96],
      dtype=int32)

In [72]:
np.sort(a)[::-1]

array([96, 95, 86, 78, 68, 64, 48, 41, 38, 30, 27, 26, 20, 20, 14],
      dtype=int32)

In [76]:
np.sort(b)

array([[ 8, 35, 43, 59],
       [25, 39, 42, 55],
       [35, 46, 56, 57],
       [35, 38, 45, 88],
       [15, 77, 90, 94],
       [ 2,  6, 57, 90]], dtype=int32)

In [74]:
np.sort(b,axis=0)

array([[38,  2, 15,  6],
       [42, 25, 35,  8],
       [46, 35, 35, 39],
       [59, 43, 55, 56],
       [77, 45, 57, 88],
       [90, 90, 57, 94]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
np.append(a,200)

array([ 49,  94,  58,  48,  49,   8,   5,  60,  15,  69,   8,  72,  70,
        15,   9, 200])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
e = np.array([1,1,2,3,4,4,4,4,5,5,5,9,7,8,9,8])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 7, 8, 9])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [15]:
a.shape

(15,)

In [16]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [17]:
np.expand_dims(a,axis = 1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([49, 94, 58, 48, 49,  8,  5, 60, 15, 69,  8, 72, 70, 15,  9],
      dtype=int32)

In [19]:
np.where(a>50)

(array([ 1,  2,  7,  9, 11, 12]),)

In [20]:
np.where(a>50,0,a)

array([49,  0,  0, 48, 49,  8,  5,  0, 15,  0,  8,  0,  0, 15,  9],
      dtype=int32)

In [21]:
np.where(a%2 == 0,0,a)

array([49,  0,  0,  0, 49,  0,  5,  0, 15, 69,  0,  0,  0, 15,  9],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
a = np.random.randint(1,100,15)
a

array([62, 65, 27, 32, 72, 45, 97, 29, 93, 81, 44, 19, 78, 40, 57],
      dtype=int32)

In [23]:
np.argmax(a)

np.int64(6)

In [78]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[45, 97, 59, 12],
       [73, 38, 15, 63],
       [96, 31, 54, 43],
       [98, 49, 31,  1],
       [34, 72, 58, 87],
       [98, 83, 87, 57]], dtype=int32)

In [82]:
np.argmax(b)

np.int64(12)

In [83]:
np.argmax(b,axis=0)

array([3, 0, 5, 4])

In [80]:
np.argmax(b,axis=1)

array([1, 0, 0, 0, 3, 0])

In [27]:
np.argmin(a)

np.int64(11)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [28]:
a

array([62, 65, 27, 32, 72, 45, 97, 29, 93, 81, 44, 19, 78, 40, 57],
      dtype=int32)

In [29]:
np.cumsum(a)

array([ 62, 127, 154, 186, 258, 303, 400, 429, 522, 603, 647, 666, 744,
       784, 841])

In [30]:
b

array([[14, 68, 57,  4],
       [30, 37, 91, 40],
       [71, 77, 35, 75],
       [57, 44, 92, 32],
       [38, 91, 47, 71],
       [ 4, 67, 34,  1]], dtype=int32)

In [31]:
np.cumsum(b,axis=1)

array([[ 14,  82, 139, 143],
       [ 30,  67, 158, 198],
       [ 71, 148, 183, 258],
       [ 57, 101, 193, 225],
       [ 38, 129, 176, 247],
       [  4,  71, 105, 106]])

In [32]:
np.cumprod(a)

array([                  62,                 4030,               108810,
                    3481920,            250698240,          11281420800,
              1094297817600,       31734636710400,     2951321214067200,
         239057018339443200, -7928235266774050816, -3062517479030552576,
         931309593841070080,   358895606223699968,  2010305481041346560])

In [33]:
np.cumprod(b)

array([                  14,                  952,                54264,
                     217056,              6511680,            240932160,
                21924826560,         876993062400,       62266507430400,
           4794521072140800,   167808237524928000, -5861126259339951616,
       -2042803455605313024,  2350368321913985024, -5127043268427997184,
        1955312073690054656,   514882505383870464, -8485924231196442624,
        6989930755377332224, -1777006358367305728, -7108025433469222912,
        3377641874010406912,  4159359274096525312,  4159359274096525312])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [34]:
a

array([62, 65, 27, 32, 72, 45, 97, 29, 93, 81, 44, 19, 78, 40, 57],
      dtype=int32)

In [85]:
np.percentile(b,50,axis=1)

array([52. , 50.5, 48.5, 40. , 65. , 85. ])

In [86]:
np.median(b)

np.float64(57.5)

In [87]:
np.percentile(b,50)

np.float64(57.5)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [88]:
a

array([86, 95, 48, 20, 26, 78, 27, 38, 68, 14, 64, 20, 41, 96, 30],
      dtype=int32)

In [89]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [39]:
salary = np.array([10000, 20000, 30000, 40000, 50000])
experiance = np.array([1, 5, 3, -2, 8])
np.corrcoef(salary, experiance)

array([[1.        , 0.29065918],
       [0.29065918, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [91]:
a

array([86, 95, 48, 20, 26, 78, 27, 38, 68, 14, 64, 20, 41, 96, 30],
      dtype=int32)

In [92]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([20, 20, 30], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [94]:
a

array([86, 95, 48, 20, 26, 78, 27, 38, 68, 14, 64, 20, 41, 96, 30],
      dtype=int32)

In [95]:
np.flip(a)

array([30, 96, 41, 20, 64, 14, 68, 38, 27, 78, 26, 20, 48, 95, 86],
      dtype=int32)

In [93]:
b

array([[45, 97, 59, 12],
       [73, 38, 15, 63],
       [96, 31, 54, 43],
       [98, 49, 31,  1],
       [34, 72, 58, 87],
       [98, 83, 87, 57]], dtype=int32)

In [96]:
np.flip(b,axis=1)

array([[12, 59, 97, 45],
       [63, 15, 38, 73],
       [43, 54, 31, 96],
       [ 1, 31, 49, 98],
       [87, 58, 72, 34],
       [57, 87, 83, 98]], dtype=int32)

In [97]:
np.flip(b)

array([[57, 87, 83, 98],
       [87, 58, 72, 34],
       [ 1, 31, 49, 98],
       [43, 54, 31, 96],
       [63, 15, 38, 73],
       [12, 59, 97, 45]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [98]:
a

array([86, 95, 48, 20, 26, 78, 27, 38, 68, 14, 64, 20, 41, 96, 30],
      dtype=int32)

In [99]:
np.put(a,[0,1],[110,530])

In [101]:
a

array([110, 530,  48,  20,  26,  78,  27,  38,  68,  14,  64,  20,  41,
        96,  30], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [102]:
a

array([110, 530,  48,  20,  26,  78,  27,  38,  68,  14,  64,  20,  41,
        96,  30], dtype=int32)

In [103]:
np.delete(a,[0,2,4])

array([530,  20,  78,  27,  38,  68,  14,  64,  20,  41,  96,  30],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [51]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
np.intersect1d(m,n)

array([3, 4, 5])

In [53]:
np.setdiff1d(m,n)

array([1, 2])

In [54]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [104]:
m[np.isin(m,78)]

array([], dtype=int64)

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [56]:
a

array([110, 530,  27,  32,  72,  45,  97,  29,  93,  81,  44,  19,  78,
        40,  57], dtype=int32)

In [57]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 27, 32, 72, 45, 75, 29, 75, 75, 44, 25, 75, 40, 57],
      dtype=int32)

In [58]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [59]:
np.swapaxes(a, 0, 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
a = np.random.rand(2, 3, 4)  # Shape (2, 3, 4)
b = np.swapaxes(a, 0, 2)     # Now shape becomes (4, 3, 2)
a

array([[[0.87951534, 0.00661045, 0.70841781, 0.6428379 ],
        [0.63227968, 0.17326697, 0.77245768, 0.88514556],
        [0.82556173, 0.288682  , 0.28801422, 0.28232544]],

       [[0.46029256, 0.39153428, 0.15105118, 0.44883819],
        [0.28255981, 0.17363167, 0.19271563, 0.01201355],
        [0.58658354, 0.16999953, 0.38604633, 0.25223438]]])

In [61]:
b

array([[[0.87951534, 0.46029256],
        [0.63227968, 0.28255981],
        [0.82556173, 0.58658354]],

       [[0.00661045, 0.39153428],
        [0.17326697, 0.17363167],
        [0.288682  , 0.16999953]],

       [[0.70841781, 0.15105118],
        [0.77245768, 0.19271563],
        [0.28801422, 0.38604633]],

       [[0.6428379 , 0.44883819],
        [0.88514556, 0.01201355],
        [0.28232544, 0.25223438]]])

In [105]:
np.random.uniform(0, 41, 10)

array([13.30029724, 19.08688685, 25.03143463,  4.97803464, 13.25382674,
        0.3229597 , 25.60935265, 33.44683342, 11.73336452,  9.8434995 ])

In [63]:
np.count_nonzero(a, axis=None, keepdims=False)


24

In [106]:
np.tile(a, 3)


array([110, 530,  48,  20,  26,  78,  27,  38,  68,  14,  64,  20,  41,
        96,  30, 110, 530,  48,  20,  26,  78,  27,  38,  68,  14,  64,
        20,  41,  96,  30, 110, 530,  48,  20,  26,  78,  27,  38,  68,
        14,  64,  20,  41,  96,  30], dtype=int32)

In [107]:
np.repeat(a, 3)

array([110, 110, 110, 530, 530, 530,  48,  48,  48,  20,  20,  20,  26,
        26,  26,  78,  78,  78,  27,  27,  27,  38,  38,  38,  68,  68,
        68,  14,  14,  14,  64,  64,  64,  20,  20,  20,  41,  41,  41,
        96,  96,  96,  30,  30,  30], dtype=int32)