### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

# Create a zero vector of size 10
a = np.zeros(10)

# Set the fifth element (index 4) to 1
a[4] = 1

print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [2]:
import numpy as np

# Take input and convert to integers
a = int(input("Enter a number (lower bound): "))
b = int(input("Enter a number (upper bound): "))

# Generate an array of 10 random integers between a and b
array = np.random.randint(a, b, size=10)

print("Array:", array)
print("Sum:", np.sum(array))
print("Average:", np.mean(array))


Array: [219  48 193 202 119  48 152 209 231  97]
Sum: 1518
Average: 151.8


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [3]:
import numpy as np

def create_border_array(a, b):
    # Create an array of all ones
    arr = np.ones((a, b), dtype=int)
    
    # Set the inner elements to 0
    arr[1:-1, 1:-1] = 0
    
    return arr

# Example usage:
print(create_border_array(4, 4))


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [4]:
import numpy as np

# Generate 10 values between 0 and 1 (exclusive)
vec = np.random.uniform(low=0.0001, high=0.9999, size=10)
print(vec)


[0.45480559 0.80223723 0.97885312 0.57713163 0.23235281 0.1481155
 0.27999535 0.8400501  0.56642057 0.68081814]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [22]:
import numpy as np

# Create a "rectangular identity-like" matrix of shape (3, 4)
print(np.eye(3, 4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [25]:
import numpy as np

# Create a 5x5 matrix with row values from 0 to 4
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```

In [7]:
import numpy as np

# Step 1: Generate random vector
np.random.seed(0)  # Optional: for reproducibility
random_coords = np.random.randint(1, 101, size=(10, 2))

# Step 2: Define the reference point
point = np.array([2, 3])

# Step 3: Compute Euclidean distances
distances = np.linalg.norm(random_coords - point, axis=1)

# Step 4: Convert to integer type
int_distances = distances.astype(int)

# Output
print("Random Coordinates:\n", random_coords)
print("Distance Array:\n", int_distances)


Random Coordinates:
 [[45 48]
 [65 68]
 [68 10]
 [84 22]
 [37 88]
 [71 89]
 [89 13]
 [59 66]
 [40 88]
 [47 89]]
Distance Array:
 [ 62  90  66  84  91 110  87  84  93  97]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
import numpy as np

shape = (6, 7, 8)
flat_index = 99
# Get the (x, y, z) index from flat index
index = np.unravel_index(flat_index, shape)

print("Index of 100th element:", index)


Index of 100th element: (np.int64(1), np.int64(5), np.int64(3))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [9]:
import numpy as np

# Step 1: Read input
input_str = input()
print(input_str.split())

# Step 2: Convert to list of floats
arr = np.array(input_str.split(), dtype=float)

# Step 3: Reverse the array
reversed_arr = arr[::-1]

# Step 4: Print the result
print(reversed_arr)


['12']
[12.]


**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [10]:
import numpy as np

# Read space-separated input from user
input_str = input().strip()

# Handle empty input separately
if input_str == "":
    arr = np.array([])
else:
    arr = np.array(input_str.split(), dtype=float)

# Print number of elements
print("elements_count :", arr.size)


elements_count : 1


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [11]:
import numpy as np

def softmax(x):
    # Validate input type
    if not isinstance(x, np.ndarray):
        raise TypeError("Input must be a NumPy array.")
    
    # Validate shape (must be 1D)
    if x.ndim != 1:
        raise ValueError("Input must be a 1D NumPy array.")
    
    # Numerical stability: subtract max before exponentiation
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

arr = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
print(softmax(arr))

arr = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098, 68.82830233, 91.52064278])
print(softmax(arr))


[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [30]:
import numpy as np

def vertical_stack(*arrays):
    return np.vstack(arrays)

a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

result = vertical_stack(a, b)
print(result)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.

**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [13]:
import numpy as np
from datetime import datetime

def date_array(start, end):
    # Check if both inputs are strings
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both start and end dates must be strings.")

    # Try to parse the dates
    try:
        start_date = np.datetime64(datetime.strptime(start, "%Y-%m-%d").date())
        end_date = np.datetime64(datetime.strptime(end, "%Y-%m-%d").date())
    except ValueError:
        raise ValueError("Date format must be YYYY-MM-DD (e.g., '2022-12-6').")

    # Check if dates are from the same year
    if start_date.astype('datetime64[Y]') != end_date.astype('datetime64[Y]'):
        raise ValueError("Start and end dates must be from the same year.")

    # Generate the date range (inclusive of end date)
    return np.arange(start_date, end_date + np.timedelta64(1, 'D')).astype(str)

print(date_array(start='2020-09-15', end='2020-09-25'))
print(date_array(start='2022-12-01', end='2022-12-06'))
print(date_array(start='2020-11-25', end='2020-11-30'))


['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']
['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
 '2022-12-06']
['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


### `Q-14:` Subtract the mean of each row from a matrix.

In [14]:
import numpy as np

def row_center(matrix):
    """
    Subtract the mean of each row from a 2-D NumPy array.

    Parameters
    ----------
    matrix : np.ndarray
        A two-dimensional NumPy array.

    Returns
    -------
    np.ndarray
        A new array where each row has zero mean.

    Raises
    ------
    TypeError
        If `matrix` is not a NumPy array.
    ValueError
        If `matrix` is not two-dimensional.
    """
    if not isinstance(matrix, np.ndarray):
        raise TypeError("Input must be a NumPy array.")
    if matrix.ndim != 2:
        raise ValueError("Input must be a 2-D matrix.")

    # Compute row means (shape: [n_rows, 1]) and subtract
    return matrix - matrix.mean(axis=1, keepdims=True)
A = np.array([[ 1,  2,  3],
              [10, 20, 30],
              [ 4,  0, -4]])

print(row_center(A))


[[ -1.   0.   1.]
 [-10.   0.  10.]
 [  4.   0.  -4.]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
import numpy as np

def swap_columns(matrix):
    # Make a copy to avoid modifying the original
    result = matrix.copy()
    result[:, [0, 1]] = result[:, [1, 0]]
    return result
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

swapped = swap_columns(arr)
print(swapped)


[[20 10 30]
 [50 40 60]
 [80 70 90]]


### `Q-16:` Replace odd elements in arrays with -1.

In [ ]:
import numpy as np

def replace_odds(arr):
    # Make a copy to avoid modifying the original
    result = arr.copy()
    result[result % 2 != 0] = -1
    return result
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(replace_odds(a))


[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [17]:
import numpy as np

a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

result = np.maximum(a, b)
print(result)


[6 3 1 7 8]


### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [18]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2898, 9894,  538, 6217, 6922],
       [6037, 2164, 5073, 4852, 7878],
       [2047, 1872, 7600, 2497, 8292],
       [ 756,  798,  660, 3220, 8616],
       [7457, 3338, 2746, 4736, 8737],
       [6688,  715, 2293, 8344, 1208],
       [6173, 8995, 7222, 6022, 3623],
       [3561, 8949, 1642, 4985, 4354]], dtype=int32)

In [19]:
import numpy as np

# Step 1: Create the array
arr1 = np.random.randint(1, 10000, size=40).reshape(8, 5)

# Step 2: Alternate columns
alternate_columns = arr1[:, ::2]

# Step 3: Normalize
normalized_arr = (arr1 - arr1.min()) / (arr1.max() - arr1.min())

# Print results
print("Original Array:\n", arr1)
print("\nAlternate Columns:\n", alternate_columns)
print("\nNormalized Array:\n", normalized_arr)


Original Array:
 [[8623 7251 4188 2660 9782]
 [2957 2252 4421 7109 1072]
 [5252 7013 9397 3919 9360]
 [1685 7099 2958 4470 8753]
 [9798 5796 1473 7264 7366]
 [8449 6002 3763 9009 2436]
 [1635  974 4465 8394 2419]
 [3456 6168 5820 6522 6243]]

Alternate Columns:
 [[8623 4188 9782]
 [2957 4421 1072]
 [5252 9397 9360]
 [1685 2958 8753]
 [9798 1473 7366]
 [8449 3763 2436]
 [1635 4465 2419]
 [3456 5820 6243]]

Normalized Array:
 [[0.86684044 0.71135539 0.36423391 0.19106981 0.99818676]
 [0.22472801 0.14483228 0.39063917 0.69526292 0.01110607]
 [0.48481414 0.6843835  0.95455576 0.33374887 0.95036265]
 [0.0805757  0.69412965 0.22484134 0.3961922  0.88157298]
 [1.         0.54646419 0.05655032 0.71282865 0.72438803]
 [0.84712149 0.56980961 0.31606981 0.91058477 0.1656845 ]
 [0.07490934 0.         0.39562557 0.84088849 0.16375793]
 [0.28127833 0.58862194 0.54918404 0.6287398  0.59712149]]


### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
import numpy as np

def nth_largest(arr, n):
    # Use np.partition for efficient partial sorting
    return np.partition(arr, -n)[-n]

a = np.array([12, 34, 40, 7, 1, 0])

print(nth_largest(a, 3))  # Output: 12
print(nth_largest(a, 1))  # Output: 40


12
40


### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a. 
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [21]:
import numpy as np

a = np.array([1, 2, 3])
result = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print(result)
# Print as comma-separated
print("array([{}])".format(", ".join(map(str, result))))


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
