### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [1]:
import numpy as np

# Create a random 3x4 matrix with values between 0 and 100
arr = np.random.randint(0, 101, size=(3, 4))

# i. Sort the matrix
sorted_matrix = np.sort(arr, axis=None).reshape(arr.shape)

# ii. Sort based on the 2nd column
sorted_by_second_column = arr[arr[:, 1].argsort()]

# iii. Sort based on the max value in each row (ascending)
sorted_by_max_row = arr[np.argmax(arr, axis=1).argsort()]

# iv. Sort based on element values (flatten the array and sort)
sorted_by_elements = np.sort(arr, axis=None).reshape(arr.shape)

# Output the results
print("Original Array:")
print(arr)
print("\nSorted (by elements):")
print(sorted_matrix)
print("\nSorted by 2nd column:")
print(sorted_by_second_column)
print("\nSorted by row max value (ascending):")
print(sorted_by_max_row)
print("\nSorted by element values:")
print(sorted_by_elements)


Original Array:
[[50 26  0 21]
 [93 30 74 96]
 [21 64 33 70]]

Sorted (by elements):
[[ 0 21 21 26]
 [30 33 50 64]
 [70 74 93 96]]

Sorted by 2nd column:
[[50 26  0 21]
 [93 30 74 96]
 [21 64 33 70]]

Sorted by row max value (ascending):
[[50 26  0 21]
 [93 30 74 96]
 [21 64 33 70]]

Sorted by element values:
[[ 0 21 21 26]
 [30 33 50 64]
 [70 74 93 96]]


### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [2]:
import numpy as np

# Step 1: Given Data Setup
marks = np.array([
    [13, 10,  9, 33],
    [63, 46, 90, 42],
    [39, 76, 13, 29],
    [82,  9, 29, 78],
    [67, 61, 59, 36]
])

extra_subject = np.array([41, 87, 72, 36, 92])  # Extra subject marks for 5 students

rec1 = [77, 83, 98, 95, 89]  # New student 1 (with 5 subjects)
rec2 = [92, 71, 52, 61, 53]  # New student 2 (with 5 subjects)

# Step 2: i. Add marks of the extra subject to the existing array
extra_subject = extra_subject.reshape(5, 1)  # Reshape extra_subject to be a column
marks = np.hstack((marks, extra_subject))  # Add it as a new column to the existing marks array

# Print marks after adding extra subject
print("Marks after adding extra subject:")
print(marks)

# Step 3: ii. Add two new students' marks
new_students = np.array([rec1, rec2])  # Create a 2x5 array for the new records
marks = np.vstack((marks, new_students))  # Append to the existing marks array

# Print marks after adding new students
print("\nMarks after adding two new students:")
print(marks)

# Step 4: iii. Add extra column with total of all subject marks
total_marks = np.sum(marks, axis=1).reshape(-1, 1)  # Sum along axis 1 (row-wise)
marks = np.hstack((marks, total_marks))  # Add the total marks as a new column

# Print marks after adding total column
print("\nMarks after adding total marks column:")
print(marks)

# Step 5: iv. Sort by total marks in non-ascending order & show top 2 rows
sorted_marks = marks[marks[:, -1].argsort()[::-1]]  # Sort by total marks in descending order
top_2 = sorted_marks[:2]  # Get the top 2 students

# Print the top 2 students
print("\nTop 2 students by total marks:")
print(top_2)


Marks after adding extra subject:
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

Marks after adding two new students:
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

Marks after adding total marks column:
[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

Top 2 students by total marks:
[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [3]:
import numpy as np

# Given 2D array
arr = np.array([
    [1, 2, 3, 3, 1, 1],
    [0, 9, 1, 2, 8, 8],
    [1, 2, 3, 8, 8, 8],
    [1, 2, 3, 3, 1, 1]
])

# Row-wise unique arrays
row_wise_unique = np.unique(arr, axis=0)

# Column-wise unique arrays
col_wise_unique = np.unique(arr, axis=1)

# Printing the results
print("Row-wise unique arrays:")
print(row_wise_unique)

print("\nColumn-wise unique arrays:")
print(col_wise_unique)


Row-wise unique arrays:
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Column-wise unique arrays:
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


### `Q-4:` Flip given 2-D array along both axes at the same time.

In [4]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

flipped = arr[::-1, ::-1]
print(flipped)
flippe = np.flip(arr)
print(flippe)


[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [10, -3, 30, 4, 5],
                [3, 2, 5, -4, 5],
                [9, 7, 3, 6, 5]])

X = 6

# Check which rows have any element greater than X
row_indices = np.where(np.any(arr > X, axis=1))[0]

print(row_indices)


[1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [6]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
flat_array = np.concatenate((arr1, arr2, arr3))
print(flat_array)


[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [9]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(400)

# Generate the array
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

# Flatten to 1D for simplicity (or use arr[0])
arr_flat = arr.flatten()  # Shape: (200,)

# Find minimum and maximum
min_val = np.min(arr_flat)
max_val = np.max(arr_flat)
min_idx = np.argmin(arr_flat)
max_idx = np.argmax(arr_flat)

# Ensure distinct indices (if min and max are at the same index, handle duplicates)
if min_idx == max_idx:
    # Find another occurrence of min or max if possible
    min_indices = np.where(arr_flat == min_val)[0]
    max_indices = np.where(arr_flat == max_val)[0]
    if len(min_indices) > 1:
        min_idx = min_indices[1]  # Take second occurrence
    elif len(max_indices) > 1:
        max_idx = max_indices[1]
    else:
        raise ValueError("Cannot remove min and max; only one occurrence exists")

# Remove min and max elements
indices_to_remove = [min_idx, max_idx]
modified_arr = np.delete(arr_flat, indices_to_remove)

# Reshape back to (1, 198) if needed
modified_arr = modified_arr.reshape(1, -1)  # -1 infers 198

# Print results
print("Original Array Shape:", arr.shape)
print("Minimum Value:", min_val)
print("Maximum Value:", max_val)
print("Modified Array Shape:", modified_arr.shape)
print("Modified Array:\n", modified_arr)

Original Array Shape: (1, 200)
Minimum Value: 103
Maximum Value: 998
Modified Array Shape: (1, 198)
Modified Array:
 [[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
  323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
  270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
  620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
  426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
  922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
  695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
  761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [12]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(400)

# Generate the array with values in [100, 700]
arr = np.random.randint(100, 701, 200).reshape((1, 200))

# Step 1: Limit elements to [100, 200]
limited_arr = np.clip(arr, a_min=100, a_max=200)

# Step 2: Sort the array
sorted_arr = np.sort(limited_arr, axis=None).reshape(1, 200)

# Step 3: Compute cumulative sum
cumsum_arr = np.cumsum(sorted_arr, axis=1)

# Print results
print("Original Array Shape:", arr.shape)
print("Original Array (first 10 elements):\n", arr[0, :10])
print("\nLimited Array Shape (elements in [100, 200]):", limited_arr.shape)
print("Limited Array (first 10 elements):\n", limited_arr[0, :10])
print("\nSorted Array Shape:", sorted_arr.shape)
print("Sorted Array (first 10 elements):\n", sorted_arr[0, :10])
print("\nCumulative Sum Array Shape:", cumsum_arr.shape)
print("Cumulative Sum Array (first 10 elements):\n", cumsum_arr[0, :10])

Original Array Shape: (1, 200)
Original Array (first 10 elements):
 [448 563 418 240 507 362 345 236 291 298]

Limited Array Shape (elements in [100, 200]): (1, 200)
Limited Array (first 10 elements):
 [200 200 200 200 200 200 200 200 200 200]

Sorted Array Shape: (1, 200)
Sorted Array (first 10 elements):
 [100 103 103 110 117 123 123 129 130 131]

Cumulative Sum Array Shape: (1, 200)
Cumulative Sum Array (first 10 elements):
 [ 100  203  306  416  533  656  779  908 1038 1169]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [13]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(400)

# Generate the array with values in [0, 1]
arr = np.random.uniform(0, 1, 200)

# Step 1: Round elements to 3 decimal places
arr_rounded = np.round(arr, decimals=3)

# Step 2: Compute percentiles and extrema
percentile_0 = np.percentile(arr_rounded, 0)
percentile_100 = np.percentile(arr_rounded, 100)
percentile_50 = np.percentile(arr_rounded, 50)
percentile_51 = np.percentile(arr_rounded, 51)
min_val = np.min(arr_rounded)
max_val = np.max(arr_rounded)

# Step 3: Compare 0th percentile with minimum and 100th percentile with maximum
is_0th_equal_min = percentile_0 == min_val
is_100th_equal_max = percentile_100 == max_val

# Step 4: Compute difference between 51st and 50th percentiles
percentile_diff = percentile_51 - percentile_50

# Print results
print("Rounded Array Shape:", arr_rounded.shape)
print("Rounded Array (first 10 elements):\n", arr_rounded[:10])
print("\nMinimum Value:", min_val)
print("0th Percentile:", percentile_0)
print("Is 0th Percentile == Minimum?:", is_0th_equal_min)
print("\nMaximum Value:", max_val)
print("100th Percentile:", percentile_100)
print("Is 100th Percentile == Maximum?:", is_100th_equal_max)
print("\n50th Percentile:", percentile_50)
print("51st Percentile:", percentile_51)
print("Difference (51st - 50th Percentile):", percentile_diff)

Rounded Array Shape: (200,)
Rounded Array (first 10 elements):
 [0.669 0.226 0.859 0.29  0.148 0.012 0.776 0.405 0.856 0.539]

Minimum Value: 0.001
0th Percentile: 0.001
Is 0th Percentile == Minimum?: True

Maximum Value: 0.997
100th Percentile: 0.997
Is 100th Percentile == Maximum?: True

50th Percentile: 0.509
51st Percentile: 0.5149199999999999
Difference (51st - 50th Percentile): 0.005919999999999925
